### PR TITLE
Create SunKit.yml

### PR DESCRIPTION
**Pull request by davideilmito**

### CODE REVIEW

**Review by seldon1000 — COMMENTED** [review]
What happens when new Xcode versions are available?

**Comment by davideilmito** [comment]
Since @retroactive keyword has been added on latest commit it is necessary to run the build through an Xcode version 16 or higher. A new Xcode version will be forced if new keywords/function will not be anymore compatible with Xcode 16.1.

**Comment by davideilmito** [comment]
@seldon1000  I think we shall keep `@retroactive` keyword in order to not have any warnings.  It's ok to stick with Xcode 16.1 to run test and build.

**Review by seldon1000 — APPROVED** [review]
LGTM

**Comment by seldon1000** [comment]
The `@retroactive` keyword was added to `Date`'s extension of `Strideable` to silence a warning in Xcode 16+ releases. Given that it is unlikely that warning will cause any trouble, we could consider reverting that change instead of merging this PR. This way, we could theoretically keep retro-compatibility with previous versions of Xcode.

Otherwise, if you think it's appropriate to move forward with this PR, I'll proceed approving your changes.

**Pull request merged**
